export const config = {
  iLayer: {
    url: "https://servicesdev.arcgis.com/f126c8da131543019b05e4bfab6fc6ac/arcgis/rest/services/ChicagoCr/FeatureServer/0",
    layerType: "ArcGISFeatureLayer",
    id: 0,
    layerDefinition: {
      id: 0,
    },
  },
  version: "18.0.0",
  id: "widget_1-column",
  type: "chart",
  rotated: false,
  colorMatch: true,
  stackedType: "sideBySide",
  series: [
    {
      type: "barSeries",
      id: "FID",
      name: "FID",
      x: "Year",
      y: "count_of_FID",
      fillSymbol: {
        type: "esriSFS",
        style: "esriSFSSolid",
        color: [94, 143, 208, 255],
        outline: {
          type: "esriSLS",
          style: "esriSLSSolid",
          color: [134, 134, 134, 255],
          width: 0,
        },
      },
      dataLabels: {
        type: "chartText",
        visible: false,
        content: {
          type: "esriTS",
          color: [54, 54, 54, 255],
          font: {
            family: "Avenir Next",
            size: 10,
            style: "normal",
            weight: "normal",
            decoration: "none",
          },
          horizontalAlignment: "center",
          verticalAlignment: "top",
        },
      },
      binTemporalData: false,
      hideOversizedStackedLabels: false,
      dataTooltipVisible: true,
      query: {
        groupByFieldsForStatistics: ["Year"],
        outStatistics: [
          {
            statisticType: "count",
            onStatisticField: "FID",
            outStatisticFieldName: "count_of_FID",
          },
        ],
      },
    },
  ],
  axes: [
    {
      type: "chartAxis",
      visible: true,
      isLogarithmic: false,
      title: {
        type: "chartText",
        visible: false,
        content: {
          type: "esriTS",
          color: [24, 24, 24, 255],
          font: {
            family: "Avenir Next",
            size: 14,
            style: "normal",
            weight: "normal",
            decoration: "none",
          },
          horizontalAlignment: "center",
          verticalAlignment: "middle",
        },
      },
      labels: {
        type: "chartText",
        visible: true,
        content: {
          type: "esriTS",
          color: [68, 68, 68, 255],
          font: {
            family: "Avenir Next",
            size: 12,
            style: "normal",
            weight: "normal",
            decoration: "none",
          },
          horizontalAlignment: "center",
          verticalAlignment: "middle",
        },
      },
      valueFormat: {
        type: "category",
        characterLimit: 11,
      },
      lineSymbol: {
        type: "esriSLS",
        style: "esriSLSSolid",
        color: [139, 139, 139, 255],
        width: 1,
      },
      grid: {
        type: "esriSLS",
        style: "esriSLSDash",
        color: [213, 213, 213, 255],
        width: 0,
      },
    },
    {
      type: "chartAxis",
      visible: true,
      isLogarithmic: false,
      title: {
        type: "chartText",
        visible: false,
        content: {
          type: "esriTS",
          color: [24, 24, 24, 255],
          font: {
            family: "Avenir Next",
            size: 14,
            style: "normal",
            weight: "normal",
            decoration: "none",
          },
          horizontalAlignment: "center",
          verticalAlignment: "middle",
        },
      },
      labels: {
        type: "chartText",
        visible: true,
        content: {
          type: "esriTS",
          color: [68, 68, 68, 255],
          font: {
            family: "Avenir Next",
            size: 12,
            style: "normal",
            weight: "normal",
            decoration: "none",
          },
          horizontalAlignment: "center",
          verticalAlignment: "middle",
        },
      },
      valueFormat: {
        type: "number",
        intlOptions: {
          style: "decimal",
          useGrouping: true,
          minimumFractionDigits: 0,
          maximumFractionDigits: 0,
        },
      },
      lineSymbol: {
        type: "esriSLS",
        style: "esriSLSSolid",
        color: [139, 139, 139, 255],
        width: 1,
      },
      grid: {
        type: "esriSLS",
        style: "esriSLSDash",
        color: [213, 213, 213, 255],
        width: 0,
      },
    },
  ],
  background: [0, 0, 0, 0],
  title: {
    type: "chartText",
    visible: true,
    content: {
      type: "esriTS",
      color: [0, 0, 0, 255],
      font: {
        family: "Avenir Next",
        size: 16,
        style: "normal",
        weight: "normal",
        decoration: "none",
      },
      horizontalAlignment: "center",
      text: "Count of Year Alias",
    },
  },
  footer: {
    type: "chartText",
    visible: true,
    content: {
      type: "esriTS",
      color: [32, 32, 32, 255],
      font: {
        family: "Avenir Next",
        size: 12,
        style: "normal",
        weight: "normal",
        decoration: "none",
      },
      horizontalAlignment: "center",
      text: "",
    },
  },
  legend: {
    type: "chartLegend",
    visible: true,
    title: {
      type: "chartText",
      visible: true,
      content: {
        type: "esriTS",
        color: [32, 32, 32, 255],
        font: {
          family: "Avenir Next",
          size: 14,
          style: "normal",
          weight: "normal",
          decoration: "none",
        },
        horizontalAlignment: "center",
        text: "",
      },
    },
    body: {
      type: "esriTS",
      color: [32, 32, 32, 255],
      font: {
        family: "Avenir Next",
        size: 12,
        style: "normal",
        weight: "normal",
        decoration: "none",
      },
      horizontalAlignment: "center",
      text: "",
    },
    position: "bottom",
  },
  orderOptions: {
    orderByFields: ["Year ASC"],
    data: {
      orderType: "arcgis-charts-category",
      orderBy: "ASC",
    },
  },
};